### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by junxnone** [junxnone/issue2geojson#1]
## 方案一
- [ ] `addr2lnglat.js` 调用 `baidu map API` 解析 地址到 lnglat
- [ ] github action 调用 `addr2lnglat.js` 将 issue 内容转换为 lnglat 格式
- [ ] 将 lnglat 存储到文件

## 方案二
- [x] `addr2geojson.py` 调用 `baidu map API` 解析 地址到 lnglat
- [x] github action 调用 `addr2geojson.py` 将 issue 内容转换为 geojson格式
- [x] 将 geojson存储到repo

**Comment by junxnone** [comment]
## Python addr2lnglat
- [Python利用百度地图api批量获取地址经纬度](https://www.csdn.net/tags/NtTacg1sMDQzMTEtYmxvZwO0O0OO0O0O.html)
- [通过百度地图批量查询经纬度/通过经纬度批量查询县市](https://blog.csdn.net/weixin_51116182/article/details/120842820)

## Marker Cluster

- [百度地图 实现marker的点聚合](https://blog.csdn.net/liuyunshengsir/article/details/106237687)
